services:
  lightapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HUE_IP=${HUE_IP}
      - HUE1_IP=${HUE1_IP}
      - HUE_KEY=${HUE_KEY}
      - HUE1_KEY=${HUE1_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=${LOG_FILE:-/var/log/foxrose/app.log}
    volumes:
      - ./logs:/var/log/foxrose
      - ./config.yaml:/code/config.yaml:ro
    restart: on-failure

