services:
  eventapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FILE=${LOG_FILE}
    volumes:
      - ./logs:/var/log/foxrose
      - ./config.yaml:/code/config.yaml:ro
    restart: on-failure